spring:
  application:
    name: vfs-discovery-server

server:
  port: 8083
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka/
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost
  server:
    renewalPercentThreshold: 0.49
